# Generated by Django 5.2.8 on 2025-11-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdoctModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('product_img', models.ImageField(upload_to='')),
                ('price', models.DecimalField(choices=[('IRR', 'ریال'), ('IRT', 'تومان')], decimal_places=0, default='IRT', max_digits=10)),
                ('description', models.TextField()),
                ('attribute', models.ManyToManyField(to='shop.attributemodel')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
