# Generated by Django 5.2.8 on 2025-11-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodoctmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': ''},
        ),
    ]
