# Generated by Django 5.2.8 on 2025-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_prodoctmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('product_img', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('currency', models.CharField(choices=[('IRR', 'ریال'), ('IRT', 'تومان')], default='IRT')),
                ('description', models.TextField()),
                ('attribute', models.ManyToManyField(to='shop.attributemodel')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='ProdoctModel',
        ),
    ]
