# Generated by Django 5.2.8 on 2025-11-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productmodel_delete_prodoctmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
