# Generated by Django 5.2.8 on 2025-11-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productmodel_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
