# Generated by Django 5.2.8 on 2025-11-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productmodel_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributemodel',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attribute'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
