# Generated by Django 5.2.8 on 2025-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_attributemodel_options_productmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='Product_image_folder/%Y/%m/%d/'),
        ),
    ]
